//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TODOListApplication.Web.ToDoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToDoService.IToDoService")]
    public interface IToDoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/AddToDo", ReplyAction="http://tempuri.org/IToDoService/AddToDoResponse")]
        TODOListApplication.ServiceModel.ToDo.AddToDoRs AddToDo(TODOListApplication.ServiceModel.ToDo.AddToDoRq request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/AddToDo", ReplyAction="http://tempuri.org/IToDoService/AddToDoResponse")]
        System.Threading.Tasks.Task<TODOListApplication.ServiceModel.ToDo.AddToDoRs> AddToDoAsync(TODOListApplication.ServiceModel.ToDo.AddToDoRq request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToDoServiceChannel : TODOListApplication.Web.ToDoService.IToDoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToDoServiceClient : System.ServiceModel.ClientBase<TODOListApplication.Web.ToDoService.IToDoService>, TODOListApplication.Web.ToDoService.IToDoService {
        
        public ToDoServiceClient() {
        }
        
        public ToDoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToDoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TODOListApplication.ServiceModel.ToDo.AddToDoRs AddToDo(TODOListApplication.ServiceModel.ToDo.AddToDoRq request) {
            return base.Channel.AddToDo(request);
        }
        
        public System.Threading.Tasks.Task<TODOListApplication.ServiceModel.ToDo.AddToDoRs> AddToDoAsync(TODOListApplication.ServiceModel.ToDo.AddToDoRq request) {
            return base.Channel.AddToDoAsync(request);
        }
    }
}
